name       : enchant
version    : 2.2.13
release    : 17
source     :
    - https://github.com/AbiWord/enchant/releases/download/v2.2.13/enchant-2.2.13.tar.gz : eab9f90d79039133660029616e2a684644bd524be5dc43340d4cfc3fb3c68a20
license    : LGPL-2.1-or-later
component  : spelling
summary    : Spell check library wrapper program
description: |
    Enchant is a library wrapper program that allows the use of mulitple spell checker backends at the same time.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
setup      : |
    %configure --disable-static --with-system-myspell=yes \
               --with-myspell-dir=/usr/share/hunspell
build      : |
    %make
install    : |
    %make_install
