name       : enchant
version    : 2.2.15
release    : 20
source     :
    - https://github.com/AbiWord/enchant/releases/download/v2.2.15/enchant-2.2.15.tar.gz : 3b0f2215578115f28e2a6aa549b35128600394304bd79d6f28b0d3b3d6f46c03
license    : LGPL-2.1-or-later
component  : office.spelling
summary    : Spell check library wrapper program
description: |
    Enchant is a library wrapper program that allows the use of mulitple spell checker backends at the same time.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
setup      : |
    %configure --disable-static --with-system-myspell=yes \
               --with-myspell-dir=/usr/share/hunspell
build      : |
    %make
install    : |
    %make_install
