name       : enchant
version    : 2.5.0
release    : 25
source     :
    - https://github.com/AbiWord/enchant/releases/download/v2.5.0/enchant-2.5.0.tar.gz : 149e224cdd2ca825d874639578b6246e07f37d5b8f3970658a377a1ef46f2e15
license    : LGPL-2.1-or-later
component  : office.spelling
summary    : Spell check library wrapper program
description: |
    Enchant is a library wrapper program that allows the use of mulitple spell checker backends at the same time.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - groff
setup      : |
    %configure --disable-static --with-system-myspell=yes \
               --with-myspell-dir=/usr/share/hunspell
build      : |
    %make
install    : |
    %make_install
