name       : enchant
version    : 2.2.8
release    : 16
source     :
    - https://github.com/AbiWord/enchant/releases/download/v2.2.8/enchant-2.2.8.tar.gz : c7b5e2853f0dd0b1aafea2f9e071941affeec3a76df8e3f6d67a718c89293555
license    : LGPL-2.1-or-later
component  : spelling
summary    : Spell check library wrapper program
description: |
    Enchant is a library wrapper program that allows the use of mulitple spell checker backends at the same time.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
setup      : |
    %configure --disable-static --with-system-myspell=yes \
               --with-myspell-dir=/usr/share/hunspell
build      : |
    %make
install    : |
    %make_install
