name       : enchant
version    : 2.2.14
release    : 19
source     :
    - https://github.com/AbiWord/enchant/releases/download/v2.2.14/enchant-2.2.14.tar.gz : bf7cc9a410b54c29648c7711dc8f210e7b13768508aaf43cc9c4527d5a9c7a8e
license    : LGPL-2.1-or-later
component  : office.spelling
summary    : Spell check library wrapper program
description: |
    Enchant is a library wrapper program that allows the use of mulitple spell checker backends at the same time.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
setup      : |
    %configure --disable-static --with-system-myspell=yes \
               --with-myspell-dir=/usr/share/hunspell
build      : |
    %make
install    : |
    %make_install
