name       : enchant
version    : 1.6.0
release    : 10
source     :
    - http://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz : 2fac9e7be7e9424b2c5570d8affe568db39f7572c10ed48d4e13cddf03f7097f
license    : LGPL2.1
component  : spelling
summary    : Spell check library wrapper program
description: |
    Enchant is a library wrapper program that allows the use of mulitple spell checker backends at the same time.
builddeps  :
    - pkgconfig(hunspell)
setup      : |
    %configure --with-system-myspell=yes \
               --with-myspell-dir=/usr/share/hunspell \
               --disable-static
build      : |
    %make
install    : |
    %make_install
