name       : enchant
version    : 2.1.2
release    : 8
source     :
    - https://github.com/AbiWord/enchant/releases/download/v2.1.2/enchant-2.1.2.tar.gz : 039563bbb7340f320bd9237dac92303b3e7768152b08fc0d554d6957ae7183d8
license    : LGPL-2.1
component  : office
summary    : Spell check library wrapper program
description: |
    Enchant is a library wrapper program that allows the use of mulitple spell checker backends at the same time.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
